[package]
name = "lingers"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-complex = "0.4.0"
num-traits = "0.2.14"
pre = "0.2.1"
simba = "0.6.0"
